### ISSUE TITLE
Issues with run_test 

### ISSUE THREAD

**Issue by Anikbh11** [cameronliang/bayesvp#1]
Hey, I installed Bayesvp as suggested using pip. I'm using anaconda3 for python. 
When I run : from bayesvp.tests import run_tests
First I get : 
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/bin/bvpfit", line 7, in <module>
    from bayesvp.scripts.bvpfit import main
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/scripts/bvpfit.py", line 14, in <module>
    from bayesvp.mcmc_setup import bvp_mcmc
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/mcmc_setup.py", line 17, in <module>
    from bayesvp.config import DefineParams
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 439
    print cwd + self.output_path[1:]
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(cwd + self.output_path[1:])?

This is an easy fix so I fixed the parantheses and ran the same again, I get : 

from bayesvp.tests import run_tests
Traceback (most recent call last):
  File "/opt/anaconda-3/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-12dafa83f5a5>", line 1, in <module>
    from bayesvp.tests import run_tests
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/run_tests.py", line 3, in <module>
    from bayesvp.tests import test_config
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_config.py", line 6, in <module>
    from bayesvp.config import DefineParams
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 18, in <module>
    from bayesvp.utilities import get_transitions_params, MyParser
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/utilities.py", line 299
    pdf_tmp2  = 10**log_pdf/np.sum((10**log_pdf)*(x_stepsize))
                                                                                                    ^
TabError: inconsistent use of tabs and spaces in indentation

This also was an easy fix. After fixing this the tests actually run and all of them fail except one. Here's the output that comes with it : 
from bayesvp.tests import run_tests
test_config_file_exists (bayesvp.tests.test_config.TCConfigFile) ... ERROR
test_default_no_continuum_params (bayesvp.tests.test_config.TCConfigFile) ... ERROR
test_example_mcmc_params (bayesvp.tests.test_config.TCConfigFile) ... ERROR
test_example_priors (bayesvp.tests.test_config.TCConfigFile) ... ERROR
test_spectral_data (bayesvp.tests.test_config.TCConfigFile) ... ERROR
test_transistion_params_array (bayesvp.tests.test_config.TCConfigFile) ... ERROR
test_vp_params (bayesvp.tests.test_config.TCConfigFile) ... ERROR
test_call (bayesvp.tests.test_likelihood.TCPosterior) ... ERROR
test_default_no_continuum (bayesvp.tests.test_likelihood.TCPosterior) ... ERROR
test_lnlike (bayesvp.tests.test_likelihood.TCPosterior) ... ERROR
test_prior (bayesvp.tests.test_likelihood.TCPosterior) ... ERROR
test_general_intensity (bayesvp.tests.test_model.TCSingleVP) ... ok
test_simple_spec (bayesvp.tests.test_model.TCSingleVP) ... ERROR

======================================================================
ERROR: test_config_file_exists (bayesvp.tests.test_config.TCConfigFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_config.py", line 32, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_default_no_continuum_params (bayesvp.tests.test_config.TCConfigFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_config.py", line 32, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_example_mcmc_params (bayesvp.tests.test_config.TCConfigFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_config.py", line 32, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_example_priors (bayesvp.tests.test_config.TCConfigFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_config.py", line 32, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_spectral_data (bayesvp.tests.test_config.TCConfigFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_config.py", line 32, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_transistion_params_array (bayesvp.tests.test_config.TCConfigFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_config.py", line 32, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_vp_params (bayesvp.tests.test_config.TCConfigFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_config.py", line 32, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_call (bayesvp.tests.test_likelihood.TCPosterior)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_likelihood.py", line 21, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_default_no_continuum (bayesvp.tests.test_likelihood.TCPosterior)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_likelihood.py", line 21, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_lnlike (bayesvp.tests.test_likelihood.TCPosterior)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_likelihood.py", line 21, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_prior (bayesvp.tests.test_likelihood.TCPosterior)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_likelihood.py", line 21, in setUp
    self.config_params = DefineParams(self.config_ex)
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/config.py", line 116, in __init__
    if line[1] == 'test_path_to_spec':
TypeError: 'filter' object is not subscriptable

======================================================================
ERROR: test_simple_spec (bayesvp.tests.test_model.TCSingleVP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/tests/test_model.py", line 33, in test_simple_spec
    flux = simple_spec(self.logN,self.b,self.z,wave,'O','VI')
  File "/afs/mpa/home/mrmgehlm/.local/lib/python3.6/site-packages/bayesvp/vp_model.py", line 196, in simple_spec
    for l in xrange(n_transitions):
NameError: name 'xrange' is not defined

----------------------------------------------------------------------
Ran 13 tests in 0.014s

FAILED (errors=12)

**Comment by Anikbh11** [comment]
Edit : 

Okay so except the first 2 errors. All the other errors are python3 specific. I've managed to sort this out.
